export class Theme {
  static readonly PRIMARY = '#a78bfa';
  static readonly BACKGROUND = '#09090b';
  static readonly TERTIARY = '#34d399';
  static readonly ERROR = '#ef4444';
  
  static readonly SURFACE_0 = '#0c0c0f';
  static readonly SURFACE_1 = '#18181b';
  static readonly SURFACE_2 = '#27272a';

  static readonly TEXT_PRIMARY = '#fafafa';
  static readonly TEXT_SECONDARY = '#a1a1aa';

  static readonly BORDER_RADIUS = 8;
  static readonly BORDER_WIDTH = 1;
}